In [4]:
import pandas as pd
import numpy as np
%config IPCompliter.greedy=True

In [5]:
train = pd.read_csv("../data/raw/train.csv")
test  = pd.read_csv("../data/raw/test.csv")

In [11]:
train.head()

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,Male,0,Yes,Yes,29,Yes,No,DSL,Yes,...,Yes,Yes,No,No,One year,Yes,Mailed check,60.10,1653.85,No
1,1,Male,0,Yes,Yes,58,Yes,No,DSL,Yes,...,No,Yes,Yes,No,Two year,No,Credit card (automatic),69.50,3778.20,No
2,2,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,100.40,5841.35,No
3,3,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,69.70,70.70,Yes
4,4,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.45,70.45,Yes

In [47]:
def quick_eda(df, target=None):
    display(train.info())
    print()
    
    print("MISSING VALUES")
    miss = df.isna().sum().sort_values(ascending=False)
    miss = miss[miss > 0]
    if len(miss) == 0:
        print("No missing values")
    else:
        display(pd.DataFrame({
            "missing_cnt": miss,
            "missing_pct": (miss / len(df) * 100).round(2)
        }))
    print()    # пустая строка

    print("NUNIQUE")
    nunq = df.nunique(dropna=False).sort_values()
    display(nunq.to_frame("nunique"))
    print()

    print("NUMERICAL DESCRIBE")
    display(df.describe().T)
    print()

    print("CATEGORICAL DESCRIBE")
    cat_cols = df.select_dtypes(include=["object", "str", "category", "bool"]).columns
    if len(cat_cols) > 0:
        display(df[cat_cols].describe().T)
    else:
        print("No categorical columns")
    print()
    
    if target is not None and target in df.columns:
        print("TARGET DISTRIBUTION")
        display(df[target].value_counts(dropna=False).to_frame("count"))
        display((df[target].value_counts(normalize=True, dropna=False) * 100).round(2).to_frame("pct"))

    for col in cat_cols:
        vc = df[col].value_counts(normalize=True, dropna=False)
        
        values = [
            f"{k} ({v:.2%})"
            for k, v in vc.items()
        ]
        
        print(f"{col}: {values}")

In [61]:
quick_eda(train, target="Churn")

<class 'pandas.DataFrame'>
RangeIndex: 594194 entries, 0 to 594193
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                594194 non-null  int64
 1   gender            594194 non-null  str
 2   SeniorCitizen     594194 non-null  int64
 3   Partner           594194 non-null  str
 4   Dependents        594194 non-null  str
 5   tenure            594194 non-null  int64
 6   PhoneService      594194 non-null  str
 7   MultipleLines     594194 non-null  str
 8   InternetService   594194 non-null  str
 9   OnlineSecurity    594194 non-null  str
 10  OnlineBackup      594194 non-null  str
 11  DeviceProtection  594194 non-null  str
 12  TechSupport       594194 non-null  str
 13  StreamingTV       594194 non-null  str
 14  StreamingMovies   594194 non-null  str
 15  Contract          594194 non-null  str
 16  PaperlessBilling  594194 non-null  str
 17  PaymentMethod     594194 non-null  str
 18  MonthlyCharges    594194 non-null  float64
 19  TotalCharges      594194 non-null  float64
 20  Churn             594194 non-null  str
dtypes: float64(2), int64(3), str(16)
memory usage: 95.2 MB

None

MISSING VALUES
No missing values

NUNIQUE

                  nunique
gender                  2
SeniorCitizen           2
Partner                 2
Dependents              2
PhoneService            2
PaperlessBilling        2
Churn                   2
MultipleLines           3
TechSupport             3
StreamingTV             3
OnlineBackup            3
DeviceProtection        3
StreamingMovies         3
Contract                3
OnlineSecurity          3
InternetService         3
PaymentMethod           4
tenure                 72
MonthlyCharges       1921
TotalCharges        31910
id                 594194

NUMERICAL DESCRIBE

,count,mean,std,min,25%,50%,75%,max
id,594194.0,297096.500000,171529.177263,0.00,148548.25,297096.50,445644.75,594193.00
SeniorCitizen,594194.0,0.114102,0.317936,0.00,0.00,0.00,0.00,1.00
tenure,594194.0,36.577258,25.061922,1.00,12.00,35.00,62.00,72.00
MonthlyCharges,594194.0,65.866223,31.067444,18.25,29.90,74.10,90.80,118.75
TotalCharges,594194.0,2494.377057,2353.916710,18.80,639.65,1433.65,4263.80,8684.80

CATEGORICAL DESCRIBE

                   count unique               top    freq
gender            594194      2            Female  298738
Partner           594194      2               Yes  309554
Dependents        594194      2                No  414362
PhoneService      594194      2               Yes  557893
MultipleLines     594194      3                No  283384
InternetService   594194      3       Fiber optic  272386
OnlineSecurity    594194      3                No  289474
OnlineBackup      594194      3                No  250083
DeviceProtection  594194      3                No  247377
TechSupport       594194      3                No  288571
StreamingTV       594194      3               Yes  240301
StreamingMovies   594194      3               Yes  241435
Contract          594194      3    Month-to-month  298918
PaperlessBilling  594194      2               Yes  365579
PaymentMethod     594194      4  Electronic check  215372
Churn             594194      2                No  460377

TARGET DISTRIBUTION

        count
Churn
No     460377
Yes    133817

         pct
Churn
No     77.48
Yes    22.52

gender: ['Female (50.28%)', 'Male (49.72%)']
Partner: ['Yes (52.10%)', 'No (47.90%)']
Dependents: ['No (69.74%)', 'Yes (30.26%)']
PhoneService: ['Yes (93.89%)', 'No (6.11%)']
MultipleLines: ['No (47.69%)', 'Yes (46.20%)', 'No phone service (6.11%)']
InternetService: ['Fiber optic (45.84%)', 'DSL (30.48%)', 'No (23.68%)']
OnlineSecurity: ['No (48.72%)', 'Yes (27.60%)', 'No internet service (23.68%)']
OnlineBackup: ['No (42.09%)', 'Yes (34.23%)', 'No internet service (23.68%)']
DeviceProtection: ['No (41.63%)', 'Yes (34.68%)', 'No internet service (23.68%)']
TechSupport: ['No (48.57%)', 'Yes (27.75%)', 'No internet service (23.68%)']
StreamingTV: ['Yes (40.44%)', 'No (35.87%)', 'No internet service (23.68%)']
StreamingMovies: ['Yes (40.63%)', 'No (35.68%)', 'No internet service (23.68%)']
Contract: ['Month-to-month (50.31%)', 'Two year (31.46%)', 'One year (18.23%)']
PaperlessBilling: ['Yes (61.53%)', 'No (38.47%)']
PaymentMethod: ['Electronic check (36.25%)', 'Credit card (automatic) (22.50%)', 'Mailed check (20.83%)', 'Bank transfer (automatic) (20.42%)']
Churn: ['No (77.48%)', 'Yes (22.52%)']

In [66]:
# Считаем вероятность оттока при фиксированном типе контракта P(Churn | Contract)

cat_featrures = train.drop("Churn", axis=1).select_dtypes(include=["object", "str", "category", "bool"]).columns

for col in cat_cols:
    print(f"\n=== {col} ===")
    tbl = (
        train.groupby(col)["Churn"]
        .value_counts(normalize=True)
        .unstack(fill_value=0)
        .round(3)
    )

    tbl = tbl.sort_values(by="Yes", ascending=False)    # сортировка по churn (Yes) по убыванию

    print(tbl)

=== gender ===
Churn      No    Yes
gender
Female  0.772  0.228
Male    0.778  0.222

=== Partner ===
Churn       No    Yes
Partner
No       0.675  0.325
Yes      0.866  0.134

=== Dependents ===
Churn          No    Yes
Dependents
No          0.709  0.291
Yes         0.927  0.073

=== PhoneService ===
Churn            No    Yes
PhoneService
Yes           0.771  0.229
No            0.832  0.168

=== MultipleLines ===
Churn                No    Yes
MultipleLines
Yes               0.723  0.277
No                0.818  0.182
No phone service  0.832  0.168

=== InternetService ===
Churn               No    Yes
InternetService
Fiber optic      0.585  0.415
DSL              0.897  0.103
No               0.986  0.014

=== OnlineSecurity ===
Churn                   No    Yes
OnlineSecurity
No                   0.594  0.406
Yes                  0.913  0.087
No internet service  0.986  0.014

=== OnlineBackup ===
Churn                   No    Yes
OnlineBackup
No                   0.609  0.391
Yes                  0.833  0.167
No internet service  0.986  0.014

=== DeviceProtection ===
Churn                   No    Yes
DeviceProtection
No                   0.619  0.381
Yes                  0.817  0.183
No internet service  0.986  0.014

=== TechSupport ===
Churn                   No    Yes
TechSupport
No                   0.598  0.402
Yes                  0.904  0.096
No internet service  0.986  0.014

=== StreamingTV ===
Churn                   No    Yes
StreamingTV
No                   0.703  0.297
Yes                  0.715  0.285
No internet service  0.986  0.014

=== StreamingMovies ===
Churn                   No    Yes
StreamingMovies
No                   0.701  0.299
Yes                  0.717  0.283
No internet service  0.986  0.014

=== Contract ===
Churn              No    Yes
Contract
Month-to-month  0.579  0.421
One year        0.942  0.058
Two year        0.990  0.010

=== PaperlessBilling ===
Churn                No    Yes
PaperlessBilling
Yes               0.681  0.319
No                0.925  0.075

=== PaymentMethod ===
Churn                         No    Yes
PaymentMethod
Electronic check           0.511  0.489
Mailed check               0.920  0.080
Bank transfer (automatic)  0.923  0.077
Credit card (automatic)    0.931  0.069

In [71]:
train.head(100).to_excel("../data/raw/train.xlsx", index=False)